### ISSUE TITLE
From Sage (Dark Rosemary)'s Dad

### ISSUE THREAD

**Issue by soichih** [RiedleroD/DodgeToDrums#48]
Dear @RiedleroD and others,

Hello. My name is Soichi Hayashi I am the father of Sage Hayashi (Dark Rosemary) who passed away last Tuesday. I've been looking through Sage's computer and I've found some conversations that you were having with Sage. I believe you were the last friend that Sage has communicated on that regretful evening.

I just wanted to say thank you from the bottom of my heart, for letting Sage work with your project and your friendship. Sage showed me the game you are working on scratch, and let me play it a few days before Sage died. I've commented on how great this game was, and he was able to play it so well even though I could only survive for a very short time. You have not idea how much this game meant to Sage, how proud they were to be part of it, and how much they appreciated your friendship. 

If you are willing, please contact me at soichih@gmail.com (me) or my wife denhay@gmail.com (sage's mom) so that we could send you more through message. Please let your parents/guardians know about this message, and if they are willing to allow us to thank you and your parents, and everyone who involved our personal tragedy, it means so much to our family and helps us with our grieving process.

If I don't hear from you, I totally understand, and please know that we will always remember you as Sage's precious last friends they had on earth, and if you could remember Sage, there is nothing more that I could wish for.

Thank you,

Sage's Dad
Soichi Hayashi 

https://www.dignitymemorial.com/obituaries/bloomington-in/sage-hayashi-9318448

**Comment by RiedleroD** [comment]
Thanks, but I don't think I played that big of a role in his life, even though we were good friends. If you want to talk anyway though, you can always contact me at riedler@riedler.wien if you want. I'm wishing you and your family my best regards and I hope that you'll recover from this tragedy quickly.

Also I thought he was a girl the whole time and I'm honestly confused. It's not that important to me, but I'm just hella confused since he/she didn't ever correct me.

About the project: I've been saying that it'll continue and that I'll put a honorary message for sage right into the main menu, but I've been kind of hesitant to touch it since the incident, so I don't know what will happen to it. I hope that I can continue it, but only time will tell, I guess. If you want to add anything to the note about sage, please let me know.

best regards,
Riedler

**Comment by RiedleroD** [comment]
I'm closing this now, as the conversation is continued per mail.
